### ISSUE TITLE
Tweefly

### ISSUE THREAD

**Issue by ChapelR** [ChapelR/twine-resources#17]
New resources may not be accepted, as this guide is *curated*. Resources that don't appear to work, are extremely redundant, or are meaningfully incomplete will not be accepted.

**Resource Information**

Tweefly didn't work for me last time, I can retry it as per the dev's request. 

**Links**

https://stonedrum.de/tweefly-interactive-fiction-made-easy/

**Suggested Entry (optional)**

If you want to, you can write up an entry for the guide that we can use. By doing so, you agree to waive any rights to the content.

**Additional information (optional)**

Any further meaningful information.

**Comment by padmalcom** [comment]
Can you go into detail in what terms "Tweefly didn't work"?

**Comment by ChapelR** [comment]
Tweefly has already been added, hence why this issue is closed. You had actually already fixed it by the time this guide went live, I just had to re-test it. I don't remember what exactly the issue was offhand.
