### ISSUE TITLE
Gordian Book

### ISSUE THREAD

**Issue by hituro** [ChapelR/twine-resources#28]
**Resource Information**

Gordian Book is a tool to convert Twine/Twee3 stories into traditional Fighting-Fantasy style gamebooks, with randomised numbered paragraphs, "turn to page X" style links, and textual rules blocks. Outputs games as PDFs, Twine archives, Twee3, JSON, or HTML.

**Links**

http://ddonachie.virga.invertech.co.uk/gordian.php

**Additional information (optional)**

Disclosure, this site is by me.

**Comment by ChapelR** [comment]
Thanks. I've been swamped lately but I'll add this soon.
