### ISSUE TITLE
Sargent's Chapbook extensions

### ISSUE THREAD

**Issue by sgranade** [ChapelR/twine-resources#31]
**Resource Information**

[Sargent's Chapbook Extensions](https://github.com/sgranade/sargent-chapbook-extensions), by Stephen Granade. A collection of text manipulation modifiers and inserts.

**Links**

- [Website and documentation](https://github.com/sgranade/sargent-chapbook-extensions)
- [Demo of the extensions in action](https://sgranade.github.io/sargent-chapbook-extensions/)

**Suggested Entry (optional)**

#### Sargent's Chapbook Extensions

- [Website](https://github.com/sgranade/sargent-chapbook-extensions)
- [Demo](https://sgranade.github.io/sargent-chapbook-extensions/)

A collection of modifiers and inserts to manipulate text, like showing something different every time a passage is shown.

**Comment by ChapelR** [comment]
Thank you, I'll test it and add it this weekend!
